language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gorantemp69/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gorantemp69/docker-react npm run test